### ISSUE TITLE
Issues with refchef-menu c.uuid

### ISSUE THREAD

**Issue by JRWallace** [compbiocore/refchef#31]
```
(base) CIS2703FHTDH:local_references jwalla12$ refchef-menu -m '/Volumes/jwalla12/local_references/master.yaml'
/anaconda3/lib/python3.7/site-packages/refchef/utils.py:12: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  dict_ = yaml.load(yml)
Traceback (most recent call last):
  File "/anaconda3/bin/refchef-menu", line 41, in <module>
    menu = get_full_menu(master)
  File "/anaconda3/lib/python3.7/site-packages/refchef/table_utils.py", line 40, in get_full_menu
    levels = table[table["e"] == "levels"][["c.component", "c.files", "c.location", "c.uuid", "f", "d"]]
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2934, in __getitem__
    raise_missing=True)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "['c.uuid'] not in index"
```

**Comment by fernandogelin** [comment]
@JRWallace can I see the master.yaml file?
